Fix non-CMake `*-windows-gnullvm` cross-compilation (#1010)
* Fix non-CMake `*-windows-gnullvm` cross-compilation

Since CMake is no longer used by default to build any targets as of v1.15.3, it
has not been possible to cross-compile Rust projects that depend on `aws-lc` for
`*-windows-gnullvm` targets out of the box due to the following error:

```
warning: aws-lc-sys@0.36.0: Emitting configuration: cargo:rustc-cfg=universal
warning: aws-lc-sys@0.36.0: Building with: CC
warning: aws-lc-sys@0.36.0: Symbol Prefix: Some("aws_lc_0_36_0")
warning: aws-lc-sys@0.36.0: Target platform: 'x86_64-pc-windows-gnullvm'
warning: aws-lc-sys@0.36.0: Compilation of 'c11.c' succeeded - Ok(["/builds/project/rust/target/x86_64-pc-windows-gnullvm/release-with-debuginfo/build/aws-lc-sys-0b30765c68b88a1c/out/out-c11/7dfda64fdf5a526c-c11.o"]).
warning: aws-lc-sys@0.36.0: Using flag: -ffile-prefix-map=/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0=
warning: aws-lc-sys@0.36.0: Compilation of 'stdalign_check.c' succeeded - Ok(["/builds/project/rust/target/x86_64-pc-windows-gnullvm/release-with-debuginfo/build/aws-lc-sys-0b30765c68b88a1c/out/out-stdalign_check/7dfda64fdf5a526c-stdalign_check.o"]).
warning: aws-lc-sys@0.36.0: Compilation of 'builtin_swap_check.c' succeeded - Ok(["/builds/project/rust/target/x86_64-pc-windows-gnullvm/release-with-debuginfo/build/aws-lc-sys-0b30765c68b88a1c/out/out-builtin_swap_check/7dfda64fdf5a526c-builtin_swap_check.o"]).
warning: aws-lc-sys@0.36.0: NASM command not found or failed to execute.
warning: aws-lc-sys@0.36.0: NASM command not found or failed to execute.
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/crypto/bio/bio_addr.c:11:
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/crypto/bio/./internal.h:75:
warning: aws-lc-sys@0.36.0: /opt/llvm-mingw-20251216-ucrt-ubuntu-22.04-x86_64/x86_64-w64-mingw32/include/winsock2.h:15:2: warning: Please include winsock2.h before windows.h [-W#warnings]
warning: aws-lc-sys@0.36.0:    15 | #warning Please include winsock2.h before windows.h
warning: aws-lc-sys@0.36.0:       |  ^
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/crypto/bio/dgram.c:11:
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/crypto/bio/./internal.h:75:
warning: aws-lc-sys@0.36.0: /opt/llvm-mingw-20251216-ucrt-ubuntu-22.04-x86_64/x86_64-w64-mingw32/include/winsock2.h:15:2: warning: Please include winsock2.h before windows.h [-W#warnings]
warning: aws-lc-sys@0.36.0:    15 | #warning Please include winsock2.h before windows.h
warning: aws-lc-sys@0.36.0:       |  ^
warning: aws-lc-sys@0.36.0: 1 warning generated.
warning: aws-lc-sys@0.36.0: 1 warning generated.
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/crypto/ocsp/ocsp_http.c:18:
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/crypto/ocsp/internal.h:10:
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/include/openssl/ocsp.h:15:
warning: aws-lc-sys@0.36.0: In file included from /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/include/openssl/x509.h:82:
warning: aws-lc-sys@0.36.0: /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.36.0/aws-lc/include/openssl/pkcs7.h:281:3: error: type name requires a specifier or qualifier
warning: aws-lc-sys@0.36.0:   281 |   X509_NAME *issuer;
warning: aws-lc-sys@0.36.0:       |   ^
```

The impact of this regression can be described as fairly widespread: the set of
crates depending on `aws-lc` instead of `ring` continues is growing, with one of
the most recent high-profile adopters being
[`reqwest`](https://github.com/seanmonstar/reqwest/blob/master/CHANGELOG.md#v0130).

I noticed that `aws-lc` builds successfully when the environment variable
`AWS_LC_SYS_CMAKE_BUILDER` is set to `1`, restoring the previous default
behavior of using CMake. So rather than further complicating my build
environment by requiring CMake, I decided to investigate the differences between
the two builder implementations.

After reviewing the `CMakeLists.txt` file, I found that CMake unconditionally
defines `WIN32_LEAN_AND_MEAN` and `NOMINMAX` for all Windows targets. In
contrast, the `cc_builder` only defines these macros when using MSVC. Because
the Windows GNU/LLVM toolchains are `clang`-based, this condition does not
apply, and the necessary Windows-specific types are therefore not included.

After fixing this discrepancy so that these defines are applied consistently,
the build completes successfully again. As far as I can tell, this change should
not cause regressions on other Windows targets, since these defines are
compiler-independent.

* Fix CI for x86_64-pc-windows-gnullvm

---------

Co-authored-by: Justin Smith <justsmth@amazon.com>